### ISSUE TITLE
修改自然码为微软双拼设置无效

### ISSUE THREAD

**Issue by lihuacai168** [mutoe/rime#14]
我修改的文件是`double_pinyin_plus.custom.yaml`

修改的内容是我增加中文注释的那一行，希望把`;`来替换`Y`，实现输入`ing`的效果
```yaml
speller:
  alphabet: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA.,
  initials: zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA
  delimiter: " '"
  algebra:
    - erase/^xx$/
    - derive/^([jqxy])u$/$1v/
    - derive/^([aoe])([ioun])$/$1$1$2/
    - xform/^([aoe])(ng)?$/$1$1$2/
    - xform/iu$/Q/
    - xform/[iu]a$/W/
    - xform/[uv]an$/R/
    - xform/[uv]e$/T/
    # - xform/ing$|uai$/Y/
    - xform/uai$/Y/   
    - xform/ing$/;/ # 添加 ; 映射
 
```
修改完成之后，重新已经部署，但还是修改的效果不生效
想问一下是什么原因呢
<img width="262" alt="image" src="https://github.com/mutoe/rime/assets/11568297/db902736-0be1-41e8-a86d-4eddd0fe53ab">
